services:
  portfolio-app:
    build: .
    container_name: portfolio-web
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - PYTHONPATH=/app
      # Minimal configuration for EmailJS setup
      - SECRET_KEY=${SECRET_KEY:-default-secret-key-for-docker}
      - CONTACT_EMAIL=${CONTACT_EMAIL:-amrzakariya2018@gmail.com}
    volumes:
      # Only mount resume directory to persist uploaded resumes
      - ./static/resume:/app/static/resume:ro
      # Optional: Mount logs directory if you add logging
      # - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment the next lines if you want to use with nginx or traefik
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.portfolio.rule=Host(`yourdomain.com`)"
    #   - "traefik.http.services.portfolio.loadbalancer.server.port=5000"

# Optional: Add nginx reverse proxy
# nginx:
#   image: nginx:alpine
#   container_name: portfolio-nginx
#   restart: unless-stopped
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     - ./static:/var/www/static:ro
#   depends_on:
#     - portfolio-app

networks:
  default:
    name: portfolio-network
    driver: bridge
