services:
  portfolio-app:
    build: .
    container_name: portfolio-web-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=5000
      - PYTHONPATH=/app
    volumes:
      # Mount entire project for development (live reload)
      - .:/app
      - /app/__pycache__
    command: ["python", "app.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: portfolio-dev-network
    driver: bridge 