name: CI Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 app.py

    - name: Build Docker image
      run: |
        docker build -t portfolio-app .

    - name: Test Docker container
      run: |
        docker run -d -p 5000:5000 portfolio-app
        sleep 15 # Wait for the container to start
        curl http://127.0.0.1:5000

    - name: Clean up
      run: |
        docker ps -q | xargs docker stop
